global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'temporal'
    static_configs:
      - targets: ['temporal:7233']
  
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']






